# .github/workflows/auto-release.yml
name: 自动版本发布

on:
  push:
    branches: [ main, release ]

jobs:
  auto-release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: 设置Git用户
        run: |
          git config --global user.name 'codefish'
          git config --global user.email 'passerby365@163.com'

      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 自动版本发布
        run: |
          # 计算应该发布的版本类型 (patch, minor, major)
          COMMIT_MSG=$(git log -1 --pretty=%B)

          if [[ $COMMIT_MSG == *"BREAKING CHANGE"* ]]; then
            VERSION_TYPE="major"
          elif [[ $COMMIT_MSG == *"feat"* ]]; then
            VERSION_TYPE="minor"
          else
            VERSION_TYPE="patch"
          fi

          echo "发布 $VERSION_TYPE 版本"
          pnpm run release:$VERSION_TYPE

      - name: 推送变更
        run: |
          # 先拉取最新的变更，使用变基方式避免分支分歧
          git pull --rebase --tags origin ${{ github.ref_name }}
          # 然后推送包含标签的更改
          git push --follow-tags origin ${{ github.ref_name }}

      - name: 构建项目
        run: pnpm build

      - name: 发布到NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
